spring:
  profiles:
    group:
      default:
        - local
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

# https://10.20.30.196:9443/ibmmq/console/

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: 10.20.30.196(1414)
    user: admin
    password: passw0rd
    pool:
      enabled: true

info:
  demo:
    val1: demoVal1